### ISSUE TITLE
Error: Please use column names for `x`

### ISSUE THREAD

**Issue by mcdesignnl** [pierreroudier/dissever#4]
Hey,

When I try to run dissever, I recieve the following message:

> Error: Please use column names for `x`

When I google this error, it seems that a change in the caret package caused this error, see (for example):
https://stackoverflow.com/questions/32462588/error-in-train-from-caret

Could you have a look at this? Thank you in advance

**Comment by pierreroudier** [comment]
@mcdesignnl I'm having a hard time reproducing the bug, is there any chance you could post a reproducible example please?

Thanks,

**Comment by pierreroudier** [comment]
@mcdesignnl I'm having a hard time reproducing the bug, is there any chance you could post a reproducible example please?

Thanks,

**Comment by pierreroudier** [comment]
@mcdesignnl I figured it out -- it was a specific case when only one layer of data is available for downscaling.

Commit https://github.com/pierreroudier/dissever/commit/a37683d974013d94b8d7493ccbca9ec15cf48a1c should fix this.

Please update to version 0.2-1.
