### ISSUE TITLE
Installation failed: row names contain missing values

### ISSUE THREAD

**Issue by philament** [pierreroudier/dissever#5]
Hi, when installing dissever from github I get the following:

```
> devtools::install_github('pierreroudier/dissever')
Downloading GitHub repo pierreroudier/dissever@master
from URL https://api.github.com/repos/pierreroudier/dissever/zipball/master
Installing dissever
Installation failed: row names contain missing values
```

This happens for me on both for R 3.4.2 under Windows and for R 3.3.3 on Mac OS. Can anybody reproduce this issue?

**Comment by pierreroudier** [comment]
@philament I can reproduce this issue on my machine, and will look into it. In the meantime, you can install the CRAN release which does not seem to be affected:

```
install.packages("dissever")
```

**Comment by pierreroudier** [comment]
@philament Just pushed https://github.com/pierreroudier/dissever/commit/d72ef0a6903d129bb2727686b828e1a671e8cfbc which corrects this bug, everything should install smoothly now.

A silly mistake --- a rogue blank line in the DESCRIPTION file that I forgot to push... 

The CRAN version does not seem affected by this bug, so no version bump.

Thanks for reporting!
