### ISSUE TITLE
How to Parallel the function “dissever”?

### ISSUE THREAD

**Issue by Damonfruit** [pierreroudier/dissever#9]
Dear Pierre Roudier,
        Thanks very much for your  effort to develop the ‘dissever’ package. I have used it to downscale one precipitation grid file, which took my 4.5 mins. But I have so many file to downscale, so how can I parallel it? I have little time to do this thing. 
        I need your help.  Thanks in advance.

**Comment by pierreroudier** [comment]
`dissever` automatically detects if a parallel backend has been registered:

```
ncores <- 4 # Number of cores you want to use
cl <- parallel::makeCluster(ncores)
doParallel::registerDoParallel(cl)
# rest of your dissever code here
```
